### ISSUE TITLE
Different kind of [Errno 104]

### ISSUE THREAD

**Issue by fljxnbfz27** [n1nj4sec/pupy#99]
Hi,

I have noticed a certain issue that keeps persisting in my setup and I can't quite figure out what causes it. Everything is built with the latest version of Pupy, but even older revisions cause the same issue. 

Basically, on the server side I had around 10 or so clients connecting to me (or for example a lot of sessions from 1 client and several others from multiple different clients). At first things worked just fine, but around 48 hours into it, all sessions died out. The sessions were setup with persistence, so they were able to start calling out again, however the debug logs show that they are failing to authenticate. 

e.g: 

`2016-05-25 04:11:46,012 - INFO  - 1.2.3.4:49323 failed to authenticate, rejecting connection`

Only 1 session (sometimes 2) is able to establish out of the 10+ that are trying to establish. 

I went ahead and ran the client myself on a local machine to see what the client logs will say, and they repeatedly said this: 
```

INFO:root:connecting to 6.7.8.9:53 using transport tcp_ssl ...
INFO:root:using client options: {}
INFO:root:using transports options: {}
ERROR:root:('_ssl.c:565: The handshake operation timed out',)
```

1.2.3.4 = Client IP example
6.7.8.9 = Server IP example 

I don't know why it happens or how to solve it, at first things seemed normal but now its been like this for a while. The server is not running any sorts of firewalls that could be blocking it, and the clients are completely different machines including my own test environments that would normally be able to connect so it's most definitely not a clientside issue.

**Comment by n1nj4sec** [comment]
I had also this bug at a point but I thought it was fixed. In my case I had to restart the server to deblock the clients that looped with the same error you have.
The fix should be in pp.py, so are you sure you use the last version of the pupy client ? ( or the last exe templates ?). I you recompiled the payload templates, you need to recompile them again to have the pp.py up to date embedded into the template. And make sure to compile with a python 2.7.11 dll

**Comment by fljxnbfz27** [comment]
Thank you for the quick reply. 
I think that is probably the issue since the actual pp.py I used was an older version, I updated to the latest server, but the client remained the older version.

I will give it a try and let you know.

**Comment by fljxnbfz27** [comment]
I used the latest version of Pupy and re-did the setup. 

The issue still occurs regardless that both client and server are latest. Both my server and clients are Linux machines. 

Since you mentioned Python 2.7.11, I noticed my server is running 2.7.9, I fully upgraded to 2.7.11 on my server and the issue still remains regardless.

```
Client (Kali):
Linux CLIENT 4.4.0-kali1-amd64 #1 SMP Debian 4.4.6-1kali1 (2016-03-18) x86_64 GNU/Linux

Server (Debian 8):
Linux SERVER 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
```


Same error more or less with a bit more details: 

```
INFO:root:connecting to 6.7.8.9:53 using transport tcp_ssl ...
INFO:root:using client options: {}
INFO:root:using transports options: {}
ERROR:root:Traceback (most recent call last):
  File "<string>", line 193, in rpyc_loop
  File "<memimport>\network\launchers\simple.py", line 46, in iterate
  File "<memimport>\network\clients.py", line 99, in connect
  File "/usr/lib/python2.7/ssl.py", line 929, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 597, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 826, in do_handshake
    self._sslobj.do_handshake()
SSLError: ('_ssl.c:574: The handshake operation timed out',)
```
I am not sure if you mean restarting the actual Linux server or just Pupy when you mentioned a restart, I haven't done a server restart only a pupysh restart. 

Any ideas?

**Comment by n1nj4sec** [comment]
yes I meant a pupysh restart :) When I say the client, I mean pp.py because at a TCP level, the client initiate the connection to the server and when I say the server it's pupysh even if it is on your kali
You still have the exception, but the client doesn't reconnect a few seconds after ? If so I don't have any idea and I can't reproduce the bug, perhaps it could be your openssl version ? 
I'm currently running ``` OpenSSL 1.0.2g-fips  1 Mar 2016 ``` without any problems

**Comment by fljxnbfz27** [comment]
I updated to `OpenSSL 1.0.2h  3 May 2016` and restarted just now, but no luck. Same issue remains.
